name: Test

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  

jobs:
  build-uboot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: something-file
      - name: Test No Tag
        id: get_version
        working-directory: something-file
        run: |
          app_version=""
          if [["${{github.ref_type}}"=="tag"]]; then
              app_version=${{github.ref}}
          else
            git fetch --tags
            latest_tag=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${{github.repository}}/releases/latest" | jq -r .tag_name)
            app_version=$latest_tag
          fi
          echo "Version to check: "$app_version
          if [[ app_version =~ v([0-9]+\.[0-9]+(\.[0-9]+)?([-+][a-z0-9]+)?)$ ]]; then
            echo "Version to use(from tag): ${BASH_REMATCH[1]}"
            echo "version=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          else
            echo "Invalid tag format, will be used 0.0.1+${{ github.sha }}"
          fi
      - name: Test Tag
        run: |
          echo ${{steps.get_version.outputs.version}}
    
