name: Test

env: 
  EV_1: env_1


on:
  workflow_dispatch:

jobs:
  build-uboot:
    env:
      EV_2: env_2_${{env.EV_1}}
    runs-on: ubuntu_latest
    steps:
      - name: Clean-up artifacts
        run: |
          echo ${{env.EV_2}}
